// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import HamburguerController from "./hamburguer_controller"
application.register("hamburguer", HamburguerController)

import Notification from 'stimulus-notification'
Stimulus.register('notification', Notification)
